function returnStruct = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  LOG0015 = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a timetable.
%
%  LOG0015 = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  log0015 = importfile("/Users/karadeli/Documents/Metu-X/CurrentMeasurement 17-11/LOGS/log0015.csv", [2, Inf]);
%
%  See also READTIMETABLE.
%
% Auto-generated by MATLAB on 23-Nov-2025 18:57:58

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 18);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.PreserveVariableNames = true;
opts.VariableNames = ["timestamp", "motor_duty", "current_measured", "current_demand", "encoderFront", "encoderButt", "encoderGeared", "vel_measured", "vel_demand", "motor_pos_kalman", "motor_pos_demand", "mass_estimation", "pressure_manifold", "pressure_nozzle", "pressure_demand", "force_feedback", "force_measured", "thrust_demand"];
opts.VariableTypes = ["datetime", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "timestamp", "InputFormat", "s.SSSS", "DatetimeFormat", "preserveinput");

% Import the data
log = readtimetable(filename, opts, "RowTimes", "timestamp");

% Create a structure to hold timeseries for each variable
returnStruct = struct();

% Loop through each variable in the timetable and create a timeseries
for i = 1:width(log)
    varName = log.Properties.VariableNames{i};
    returnStruct.(varName) = timeseries(log{:, i}, log.timestamp.Second);
end
end