filename = "../LOGS/log0054.csv";
subSampleFilename = "../LOGS/log0054_subSampling.csv";

filename = "../LOGS/log0064.csv";
subSampleFilename = "../LOGS/log0064_subSampling.csv";

filename = "../LOGS/log0049.csv";
subSampleFilename = "../LOGS/log0049_subSampling.csv";
% Auto-generated by MATLAB on 01-Dec-2025 18:43:33
opts = delimitedTextImportOptions("NumVariables", 20);
opts.DataLines = [2, Inf];
opts.Delimiter = ",";
opts.VariableNames = ["timestamp", "motor_duty", "current_measured", "current_demand", "encoderFront", "encoderButt", "encoderGeared", "vel_measured", "vel_demand", "motor_pos_kalman", "motor_pos_demand", "mass_estimation", "pressure_manifold", "pressure_nozzle", "pressure_demand", "force_feedback", "force_measured", "thrust_demand", "encoder_48", "current_48"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string", "string"];
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts = setvaropts(opts, ["encoder_48", "current_48"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["encoder_48", "current_48"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, ["timestamp", "motor_duty", "current_measured", "current_demand", "encoderFront", "encoderButt", "encoderGeared", "vel_measured", "vel_demand", "motor_pos_kalman", "motor_pos_demand", "mass_estimation", "pressure_manifold", "pressure_nozzle", "pressure_demand", "force_feedback", "force_measured", "thrust_demand"], "ThousandsSeparator", ",");
logTable = readtable(filename, opts);
opts = delimitedTextImportOptions("NumVariables", 4);
opts.DataLines = [2, Inf];
opts.Delimiter = ",";
opts.VariableNames = ["timestamp", "encoderData", "currentData", "encoderWrapped"];
opts.VariableTypes = ["double", "double", "double", "double"];
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
logSubSampleTable= readtable(subSampleFilename, opts);
clear opts

logTable.encoder_48 = arrayfun(@(s) str2num(s).', logTable.encoder_48, 'UniformOutput', false);
% logTable.encoder_48 = cellfun(@transpose, logTable.encoder_48);
logTable.current_48 = arrayfun(@(s) str2num(s).', logTable.current_48, 'UniformOutput', false);
% encoder_48 = cell2mat(logTable.encoder_48);
encoder_48 = reshape(logSubSampleTable.encoderWrapped, 48, []).';
encoder_48 = timeseries(encoder_48, logTable.timestamp);

current_48 = cell2mat(logTable.current_48);
current_48 = reshape(current_48, 48 , []).';
current_48 = timeseries(current_48, logTable.timestamp);


encoderWrapped = timeseries(logSubSampleTable.encoderWrapped,logSubSampleTable.timestamp);
currentData= timeseries(logSubSampleTable.currentData,logSubSampleTable.timestamp);

encoderButt = timeseries(logTable.encoderButt, logTable.timestamp);
currentMeasured = timeseries(logTable.current_measured, logTable.timestamp);

motorDuty = timeseries(logTable.motor_duty, logTable.timestamp);